### ISSUE TITLE
Release 1.0.27 not found on hex.pm?

### ISSUE THREAD

**Issue by joerichsen** [processone/fast_yaml#16]
First of all - thanks for a great library :-)

If I go to https://hex.pm/packages/fast_yaml version 1.0.25 seems to be the latest release?

![image](https://user-images.githubusercontent.com/1052/88903560-336ba580-d254-11ea-9ca5-0a84669c1c6b.png)

Has the 1.0.27 release not been published on hex.pm?

**Comment by prefiks** [comment]
Hello,

Yes it's not published yet, we will do this this week.

**Comment by mremond** [comment]
We released it today.

**Comment by joerichsen** [comment]
Excellent, thanks a lot :-)
