### ISSUE TITLE
 Directory "tests" missing in hex.pm package

### ISSUE THREAD

**Issue by htgoebel** [processone/fast_yaml#21]
The missing directory inhibits running the tests on the package fetched from hex.pm

**Comment by badlop** [comment]
Right, in fact all the other libraries also lack that folder. It seems test/ was deliberately kept out of the package. I wonder why, to keep package size low?

And the second doubt, what other files would be required in addition to test/ to run the tests.

**Comment by badlop** [comment]
I commented this with Prefiks, and he mentioned several interesting points:
- hex.pm is "The package manager for the Erlang ecosystem", so it's suited to install dependencies
- You want to run the tests because you edited the source code --> you are developing -> you should download the source code from github, not the hex package
- Other hex packages don't include tests folder, like Elvis, Jason, Idna...
- How exactly are you supposed to run the tests in an hex package?

**Comment by htgoebel** [comment]
> You want to run the tests because you edited the source code

No, I did not edit the source.

I'm providing packages for Guix and it is good practice to check whether the package agually works in Guix. Same would be for Debian, Fedora, ArchLinux, Gentoo, Nix, ... you name it.

**Comment by badlop** [comment]
> hex.pm is "The package manager for the Erlang ecosystem"

Do you use the package from a package manager to build a package for another package manager?

Have you considered the possibility of using the upstream source code for building the package, instead of a derived work from a second-source package manager, which may or may not contain all the files?

**Comment by htgoebel** [comment]
I assume, hex.pm is the official distribution point for Erlang packages, like PyPy, Cargo or CPAN are. Isn't it? Esp. fast_yml does not provide other release packages - only "git archived" tags.

So to anwser your question: Yes, guix does this. E.g. for Python, cargo/rust, and others.

**Comment by badlop** [comment]
> I assume, hex.pm is the **official** distribution point for Erlang packages, like PyPy, Cargo or CPAN are. Isn't it?

It is a great package manager, and may be the main distribution method for many packages. It is not mandatory, or required.

Here are the primary place to find releases of fast_yaml:
https://github.com/processone/fast_yaml/tags

Any other package you may find is derived from there. For instance, they are published in hex.pm for convenience and easy installation. But it isn't the main place. To reduce package size, some files that are useless at runtime are not included.

And as I mentioned, many other well known packages do not include tests/ in their hex.pm packages.
