### ISSUE TITLE
start app on production

### ISSUE THREAD

**Issue by MeterSoft** [processone/fast_yaml#9]
When i start my app on production mode i got error

{"Kernel pid terminated",application_controller,"{application_start_failure,fast_yaml,{bad_return,{{fast_yaml_app,start,[normal,[]]},{'EXIT',{undef,[{p1_nif_utils,get_so_path,[fast_yaml,[fast_yaml],\"fast_yaml\"],[]},{fast_yaml,load_nif,0,[{file,\"/home/property/three_taps/posting_receiver/build/deps/fast_yaml/src/fast_yaml.erl\"},{line,51}]},{fast_yaml_app,start,2,[{file,\"/home/property/three_taps/posting_receiver/build/deps/fast_yaml/src/fast_yaml_app.erl\"},{line,35}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,fast_yaml,{bad_return,{{fast_yaml_app,start,[normal,[]]},{'EXIT',{undef,[{p1_nif_utils,get_so_path,[fast_yaml,[fast_yaml],"fa

**Comment by MeterSoft** [comment]
this error after run mix release


[info] Application fast_yaml exited: exited in: :fast_yaml_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :p1_nif_utils.get_so_path/3 is undefined (module :p1_nif_utils is not available)
            :p1_nif_utils.get_so_path(:fast_yaml, [:fast_yaml], 'fast_yaml')
            (fast_yaml) /home/bohdan/work/three_taps/deps/fast_yaml/src/fast_yaml.erl:51: :fast_yaml.load_nif/0
            (fast_yaml) /home/bohdan/work/three_taps/deps/fast_yaml/src/fast_yaml_app.erl:35: :fast_yaml_app.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4

**Comment by MeterSoft** [comment]
resolved

**Comment by iwarshak** [comment]
@MeterSoft How did you resolve this issue?

**Comment by simonprev** [comment]
@MeterSoft Having the same issue right now, how did you resolve this?

**Comment by MeterSoft** [comment]
> @MeterSoft Having the same issue right now, how did you resolve this?

try install library 

> sudo apt-get install erlang-p1-utils

**Comment by simonprev** [comment]
@prefiks You seem to be the active maintainer, do you know if there is a way to use this library on Alpine (with `apk` and not `apt-get`)? The `erlang-p1-utils` is required but is not available on Alpine.

Thank you!

**Comment by badlop** [comment]
> The erlang-p1-utils is required but is not available on Alpine.

Just a small comment, in case it helps you: I see p1_utils includes only erlang code, no C or other languages code. And *.beam files compiled with a specific erlang version can be used in any other erlang machine with the same version, even if it runs a different CPU architecture or operating system software. Maybe you can copy the *.beam files of one p1_utils package into your system
